/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ujgeqvqkvxuhrciketvo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZ2VxdnFrdnh1aHJjaWtldHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTcwNDMsImV4cCI6MjA2OTYzMzA0M30.zgEyAVwkN_4m7p0224Nva40p3As-O-KtWh-madOcir0"